### ISSUE TITLE
Missing code

### ISSUE THREAD

**Issue by dcjones** [UWSEDS/homework-4-documentation-and-style-cyt1208#1]
There is no python code checked into the repository. I assume you just forgot to add it. Please check it in and I'll regrade this. 1/7 points.

**Comment by cyt1208** [comment]
I'm sorry for that because I thought the code is from hw3, I just changed it in hw3. Now I've added this code to hw4, my apoloies.

**Comment by dcjones** [comment]
Ok, looks good. 7/7 points
